services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - ollama-net

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    restart: unless-stopped
    networks:
      - ollama-net

  # Optional: Add Postgres for conversation history
  db:
    image: postgres:15-alpine
    container_name: ollama-db
    environment:
      POSTGRES_DB: ollama
      POSTGRES_USER: ollamauser
      POSTGRES_PASSWORD: ollamapass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ollama-net

volumes:
  ollama_data:
  postgres_data:

networks:
  ollama-net:
    driver: bridge
