services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    mem_limit: "4g"
    mem_reservation: "2g"
    restart: unless-stopped
    networks:
      - ollama-net

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - DATABASE_TYPE=sqlite
      - DATABASE_URL=sqlite:///data/ollama.db
    volumes:
      - ./data:/data
    mem_limit: "512m"
    restart: unless-stopped
    networks:
      - ollama-net

volumes:
  ollama_data:

networks:
  ollama-net:
    driver: bridge
